### ISSUE TITLE
TypeError: range() integer end argument expected, got float.

### ISSUE THREAD

**Issue by chrisxcai** [douban/tfmesos#27]
Hi, we got an error when running the example in tutorial. We are using single node Mesos cluster with 1 gpu. When running the mnist.py example in the tfmesos/tfmesos docker image, it says:

python ./tfmesos/examples/mnist/mnist.py --worker-gpus 1
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
2016-11-15 22:06:47,260 [INFO] [tfmesos.scheduler] Tensorflow cluster registered. ( http://192.17.237.107:5050/#/frameworks/f8104b2b-e639-452f-820a-9a12243ec708-0015 )
No handlers could be found for logger "pymesos.process"
2016-11-15 22:06:47,357 [DEBUG] [tfmesos.scheduler] exit
Traceback (most recent call last):
  File "./tfmesos/examples/mnist/mnist.py", line 31, in <module>
    with cluster(jobs_def, master=master, quiet=False) as targets:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/__init__.py", line 20, in cluster
    yield s.start()
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/scheduler.py", line 306, in start
    if readable(lfd):
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/scheduler.py", line 289, in readable
    return bool(select.select([fd], [], [], 0.1)[0])
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 23, in _handle_sigint
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 287, in _run
    if not conn.read():
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 129, in read
    self._callback.process_event(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 208, in process_event
    self.on_event(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 442, in on_event
    func(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 392, in on_offers
    self, [self._dict_cls(offer) for offer in offers]
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/scheduler.py", line 220, in resourceOffers
    offered_gpus = list(range(resource.scalar.value))
TypeError: range() integer end argument expected, got float.

It seems resource.scalar.value is a float type and causing trouble for range(). Thanks!

**Comment by windreamer** [comment]
OK, I will try to fix this ASAP

**Comment by windreamer** [comment]
And may I know which version of mesos are u using?

**Comment by chrisxiaocai** [comment]
Hi, we tried both current stable release Mesos 1.0.1 and latest source code https://github.com/apache/mesos. Both give same error.
