### ISSUE TITLE
Unable to use python3 to run mnist.py

### ISSUE THREAD

**Issue by jostep** [douban/tfmesos#40]
Following errors occur when running "python3 mnist.py mesos_master:5050": 
Extracting MNIST_data/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "mnist.py", line 30, in <module>
    mnist = read_data_sets("MNIST_data/", one_hot=True)
  File "/tfmesos/examples/mnist/input_data.py", line 195, in read_data_sets
    train_images = extract_images(local_file)
  File "/tfmesos/examples/mnist/input_data.py", line 62, in extract_images
    buf = bytestream.read(rows * cols * num_images)
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 467, in read
    buf = self._fp.read(io.DEFAULT_BUFFER_SIZE)
  File "/usr/lib/python3.5/gzip.py", line 82, in read
    return self.file.read(size)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 112, in read
    return pywrap_tensorflow.ReadFromStream(self._read_buf, length, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: reached end of file

I think it is a bug in the input_file.py to use tf.gfile , I will submit a PR to fix this shortly.

**Comment by windreamer** [comment]
fixed in #41
