### ISSUE TITLE
Driver error when using a load balancer address of mesos masters

### ISSUE THREAD

**Issue by gengmao** [douban/tfmesos#57]
Use tfrun to start a training with 5 workers and 1 parameter server. Found whenever first worker finishes, the driver got following traceback in stderr. The framework quits, and ps and all workers except worker-0 got shutdown. Then worker-0 just hang forever. 
```
I tensorflow/core/distributed_runtime/master_session.cc:1012] Start master session f5aa63fb69b3be22 with config: 

[tfrun] Process IO 2017-04-21 10:06:34,367 Failed to process event
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 148, in read
    self._callback.process_event(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 226, in process_event
    self.on_event(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 491, in on_event
    func(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 451, in on_update
    self.acknowledgeStatusUpdate(status)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 305, in acknowledgeStatusUpdate
    self._send(body)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 159, in _send
    resp = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
[tfrun] Process IO 2017-04-21 10:06:34,368 Thread abort:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 308, in _run
    if not conn.read():
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 148, in read
    self._callback.process_event(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 226, in process_event
    self.on_event(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 491, in on_event
    func(event)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 451, in on_update
    self.acknowledgeStatusUpdate(status)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 305, in acknowledgeStatusUpdate
    self._send(body)
  File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 159, in _send
    resp = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```
Mesos shows the first worker's status as FINISHED, others workers except worker-0 and parameter server are KILLED, and remain worker-0 as RUNNING. But I can kill worker-0 manually. 

I tried to let all workers signal parameter server via a FIFO queue when their real work got done, and sleep. Then I let parameter server wait until all workers signaled it and exit without sleep. I found this approach worked. All workers finished their work and exit when parameter server exits, and their status are FINISHED at the end. 

So, I wonder if it is supposed to make sure no workers exit before parameter servers? Is my approach legit? Also why there is no logs around above error - can you please elaborate what happened behind the scene?

**Comment by jostep** [comment]
Are you using dockers or directly on bare metals?

**Comment by gengmao** [comment]
I am using docker

**Comment by windreamer** [comment]
Hmm, we have encountered this too. We found using `tf.Supervisor` works mot time. But it is true sometimes we get this annoying exception and do not know why. We need to ensure all worker were exited before master and ps exit, and `tf.Supervisor` is designed for this.

If `tf.Supervisor` do not work, it should be a potential race condition or bug in tfmesos. Pls do provide me more details to help me investigate it.

**Comment by gengmao** [comment]
Did you mean "need to ensure all workers were *not* exited before master
and ps exit"?
We are using tf.Supervisor and managed_session, with some custom code in
chief worker and ps to upload model, snapshot into s3. Usually other
workers exit first but as mention above we can make them sleep as a
workaround.
Surprised there was no tfrun logs around the error trace of pymesos. Will
dig deeper when I got time.

**Comment by gengmao** [comment]
Btw I use docker-compose to test same distributed tf in containers locally,
it works fine without sleep.
Guess the first worker exit triggered something in tfmesos then caused
this. I can constantly reproduce this, so not likely a race condition

**Comment by gengmao** [comment]
Grrr. The problem seems is in other place. I put an ELB in front of all mesos masters and use the ELB  address as mesos master for tfmesos. That led to above error. When I switched to use the leader master's host name for tfmesos, there is no error. I saw other workers kept running when the first work finished. 
Sorry for the false alarm.

**Comment by gengmao** [comment]
like to keep it open and do more study about this

**Comment by gengmao** [comment]
Turns out is our load balance has a health check issue - the timeout of /mesos/state.json was set too short. Hence the master was not always available. Didn't reproduce this after fixing it. 
Also tested with kazoo and master uri like zk://zk1:2181,...zk3:2181/mesos, it works very well
