### ISSUE TITLE
__getitem__ note defined?

### ISSUE THREAD

**Issue by LuisMoralesAlonso** [douban/tfmesos#65]
Just trying the basic example plus.py, get this error message:

INFO:tfmesos.scheduler:Tensorflow cluster registered. ( http://192.168.1.30:5050/#/frameworks/003fba48-218a-484d-97d2-3ab5c89c9257-0025 )
2017-05-18 15:49:50,823 [INFO] [tfmesos.scheduler] Device /job:ps/task:0 activated @ grpc://dcos-agent-3.novalocal:46126 
INFO:tfmesos.scheduler:Device /job:ps/task:0 activated @ grpc://dcos-agent-3.novalocal:46126 
2017-05-18 15:49:50,824 [INFO] [tfmesos.scheduler] Device /job:ps/task:1 activated @ grpc://dcos-agent-3.novalocal:39951 
INFO:tfmesos.scheduler:Device /job:ps/task:1 activated @ grpc://dcos-agent-3.novalocal:39951 
2017-05-18 15:49:50,824 [INFO] [tfmesos.scheduler] Device /job:worker/task:0 activated @ grpc://dcos-agent-3.novalocal:34271 
INFO:tfmesos.scheduler:Device /job:worker/task:0 activated @ grpc://dcos-agent-3.novalocal:34271 
2017-05-18 15:49:50,825 [INFO] [tfmesos.scheduler] Device /job:worker/task:1 activated @ grpc://dcos-agent-3.novalocal:42713 
INFO:tfmesos.scheduler:Device /job:worker/task:1 activated @ grpc://dcos-agent-3.novalocal:42713 
2017-05-18 15:49:50,841 [DEBUG] [tfmesos.scheduler] exit
DEBUG:tfmesos.scheduler:exit
Traceback (most recent call last):
  File "/tmp/plus.py", line 38, in <module>
    main(sys.argv)
  File "/tmp/plus.py", line 32, in main
    with tf.Session(targets['/job:worker/task:0']) as sess:

**Comment by windreamer** [comment]
@LuisMoralesAlonso we have just upgrade the version, and the return value is changed.
pls change your script according to this:
https://github.com/douban/tfmesos/commit/53f6189d18f0a0ff4d29292d337b9c4474f2f635#diff-216fc051200fedb8cff571846b56948a

**Comment by LuisMoralesAlonso** [comment]
Thanks!!! Now it works...
