### ISSUE TITLE
tfMesos on mesos single-node cluster

### ISSUE THREAD

**Issue by jostep** [douban/tfmesos#7]
Hi,

I am trying to run tfMesos on a single-node Mesos cluster with masters and slaves (set to 127.0.1.1). However, when I run plus.py in tfMesos/examples it does not work. The error is in the _start_tf_cluster when I tries to receive an "ok" response from the Mesos slave, but it actually does not receive it. It runs fine on a Mesos cluster of more than 1 node with master and slaves using External IP addresses of different machines in the cluster

Could you please let me know the problem? I have tried using localhost, 127.0.0.1 in the Mesos configuration. But, that does not help either. Mesos seems to be running fine. It seems that there is some issue in tfMesos code expecting to receive responses from the Mesos.

Here is the stack trace:

Traceback (most recent call last):
 File "plus.py", line 44, in <module>
   main(sys.argv)
 File "plus.py", line 28, in main
   with cluster(jobs_def, master=mesos_master, quiet=False) as targets:
 File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
   return self.gen.next()
 File "build/bdist.linux-x86_64/egg/tfmesos/__init__.py", line 19, in cluster
 File "build/bdist.linux-x86_64/egg/tfmesos/scheduler.py", line 299, in start
 File "build/bdist.linux-x86_64/egg/tfmesos/scheduler.py", line 255, in _start_tf_cluster
 File "build/bdist.linux-x86_64/egg/tfmesos/utils.py", line 16, in recv
AssertionError: ''

**Comment by windreamer** [comment]
Hmm, too weird. seems something goes wrong during communications

**Comment by jostep** [comment]
The following are the stdout from plus.py running:
1. worker 1 STDOUT
Registered executor on ubuntu
Starting task 3
sh -c '/usr/bin/python -m tfmesos.server 3 ubuntu:34320'
Forked command at 38970
Shutting down
Sending SIGTERM to process tree at pid 38970
Sent SIGTERM to the following process trees:
[ 
-+- 38970 sh -c /usr/bin/python -m tfmesos.server 3 ubuntu:34320 
 \--- 38971 /usr/bin/python -m tfmesos.server 3 ubuntu:34320 
]
Command terminated with signal Terminated (pid: 38970)

worker 1 stderr:
I0810 08:19:00.489054 38928 logging.cpp:188] INFO level logging started!
I0810 08:19:00.492862 38928 exec.cpp:143] Version: 0.28.2
I0810 08:19:00.520002 38953 exec.cpp:217] Executor registered on slave fb61db66-ffc1-439d-9973-4288ff674660-S0
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/tfmesos/server.py", line 59, in <module>
  File "build/bdist.linux-x86_64/egg/tfmesos/server.py", line 27, in main
  File "build/bdist.linux-x86_64/egg/tfmesos/utils.py", line 16, in recv
AssertionError: ''
I0810 08:19:01.826639 38957 exec.cpp:390] Executor asked to shutdown

ps server  stderr:
I0810 08:19:00.470211 38927 logging.cpp:188] INFO level logging started!
I0810 08:19:00.484511 38927 exec.cpp:143] Version: 0.28.2
I0810 08:19:00.502827 38932 exec.cpp:217] Executor registered on slave fb61db66-ffc1-439d-9973-4288ff674660-S0
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/tfmesos/server.py", line 59, in <module>
  File "build/bdist.linux-x86_64/egg/tfmesos/server.py", line 27, in main
  File "build/bdist.linux-x86_64/egg/tfmesos/utils.py", line 16, in recv
AssertionError: ''
I0810 08:19:01.823976 38934 exec.cpp:390] Executor asked to shutdown


Ps server stdout
Registered executor on ubuntu
Starting task 0
sh -c '/usr/bin/python -m tfmesos.server 0 ubuntu:34320'
Forked command at 38972

Shutting down
Sending SIGTERM to process tree at pid 38972
Sent SIGTERM to the following process trees:
[ 
--- 38972 ()
]
Command exited with status 134 (pid: 38972)

**Comment by jostep** [comment]
worker 0: stderr
I0810 08:19:00.465234 38926 logging.cpp:188] INFO level logging started!
I0810 08:19:00.480406 38926 exec.cpp:143] Version: 0.28.2
I0810 08:19:00.497074 38940 exec.cpp:217] Executor registered on slave fb61db66-ffc1-439d-9973-4288ff674660-S0
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
I0810 08:19:01.823484 38943 exec.cpp:390] Executor asked to shutdown
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/tfmesos/server.py", line 59, in <module>
  File "build/bdist.linux-x86_64/egg/tfmesos/server.py", line 27, in main
  File "build/bdist.linux-x86_64/egg/tfmesos/utils.py", line 16, in recv
AssertionError: ''



worker 0 stdout:
Registered executor on ubuntu
Starting task 2
Forked command at 38966
sh -c '/usr/bin/python -m tfmesos.server 2 ubuntu:34320'
nonsense II
Shutting down
Sending SIGTERM to process tree at pid 38966
Sent SIGTERM to the following process trees:
[ 
--- 38966 ()
]
Command exited with status 1 (pid: 38966)

**Comment by jostep** [comment]
ps server 0:
I0810 08:19:00.470211 38927 logging.cpp:188] INFO level logging started!
I0810 08:19:00.484511 38927 exec.cpp:143] Version: 0.28.2
I0810 08:19:00.502827 38932 exec.cpp:217] Executor registered on slave fb61db66-ffc1-439d-9973-4288ff674660-S0
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/tfmesos/server.py", line 59, in <module>
  File "build/bdist.linux-x86_64/egg/tfmesos/server.py", line 27, in main
  File "build/bdist.linux-x86_64/egg/tfmesos/utils.py", line 16, in recv
AssertionError: ''
I0810 08:19:01.823976 38934 exec.cpp:390] Executor asked to shutdown

Registered executor on ubuntu
Starting task 1
Forked command at 38968
sh -c '/usr/bin/python -m tfmesos.server 1 ubuntu:34320'
nonsense II
Shutting down
Sending SIGTERM to process tree at pid 38968
Sent SIGTERM to the following process trees:
[ 
-+- 38968 sh -c /usr/bin/python -m tfmesos.server 1 ubuntu:34320 
 \--- 38969 /usr/bin/python -m tfmesos.server 1 ubuntu:34320 
]
Command terminated with signal Terminated (pid: 38968)
