### ISSUE TITLE
program stuck when running plus.py

### ISSUE THREAD

**Issue by TungJerry** [douban/tfmesos#71]
Hello, I am just getting started to use tfmesos
I try to run the simple test(plus.py) in readme
and, program seems stuck in a loop (task stuck in running state) 
here is the traceback after a keyboard interrupt :  
`Traceback (most recent call last):
  File "/tmp/plus.py", line 38, in <module>
    main(sys.argv)
  File "/tmp/plus.py", line 22, in main
    with cluster(jobs_def, master=mesos_master, quiet=False) as c:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/__init__.py", line 19, in cluster
    s.start()
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/scheduler.py", line 328, in start
    if readable(lfd):
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/scheduler.py", line 310, in readable
    return bool(select.select([fd], [], [], 0.1)[0])
  File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 27, in _handle_sigint
    return _prev_handler(signum, frame)
KeyboardInterrupt
`
and here is traceback from mesos executor : 
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/server.py", line 78, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/server.py", line 25, in main
    response = recv(c)
  File "/usr/local/lib/python2.7/dist-packages/tfmesos/utils.py", line 13, in recv
    assert len(d) == struct.calcsize('>I'), repr(d)
AssertionError: ''`
It seems like a socket connection problem
but I can't find out what's wrong with the connection
Any idea? thanks

**Comment by windreamer** [comment]
Hi Jerry,

This example requires 4 CPUs and 4GB+ Mem to launch. Pls make sure your Mesos cluster have enough resources for this.

**Comment by TungJerry** [comment]
I see.
thanks for your reply!
